interface GpsConfig {
  // Speed validation thresholds (in m/s)
  MIN_VALID_SPEED: number;
  MAX_VALID_SPEED: number;

  // Accuracy thresholds (in meters)
  MIN_ACCURACY: number;
  MAX_ACCURACY: number;

  // Speed buffer
  SPEED_BUFFER_SIZE: number;
  MAX_CONSECUTIVE_INVALID_SPEEDS: number;

  // Mode switching thresholds (in m/s)
  ACTIVE_SPEED_THRESHOLD: number;
  PASSIVE_SPEED_THRESHOLD: number;
  PASSIVE_TIMEOUT_MS: number;
  PASSIVE_START_CONFIRMATION_COUNT: number;
  PASSIVE_START_CONFIRMATION_WINDOW_MS: number;
  LOW_SPEED_PROGRESS_RESET_DISTANCE_KM: number;
  LOW_SPEED_PROGRESS_RESET_MIN_DISPLACEMENT_KM: number;
  ACTIVE_STOP_NON_AUTOMOTIVE_CONFIRMATION_MS: number;
  ACTIVE_STOP_NON_AUTOMOTIVE_MAX_SPEED_MS: number;

  // Passive profile tuning
  PASSIVE_COARSE_DISTANCE_INTERVAL: number;
  PASSIVE_COARSE_DEFERRED_UPDATES_INTERVAL_MS: number;
  PASSIVE_COARSE_DEFERRED_UPDATES_DISTANCE: number;
  PASSIVE_PROBE_DISTANCE_INTERVAL: number;
  PASSIVE_PROBE_DEFERRED_UPDATES_INTERVAL_MS: number;
  PASSIVE_PROBE_DEFERRED_UPDATES_DISTANCE: number;
  PASSIVE_PROBE_DURATION_MS: number;
  PASSIVE_PROBE_TRIGGER_SPEED_THRESHOLD: number;
  PASSIVE_PROBE_MIN_DISPLACEMENT_KM: number;
  PASSIVE_ACTIVITY_PROBE_MIN_CONFIDENCE_SCORE: number;
  PASSIVE_ACTIVITY_PROBE_DEBOUNCE_MS: number;
  PASSIVE_ACTIVITY_PROBE_COOLDOWN_MS: number;
}

export const DEFAULT_GPS_CONFIG: GpsConfig = {
  MIN_VALID_SPEED: 0.5, // 1.8 km/h
  MAX_VALID_SPEED: 90, // 324 km/h

  MIN_ACCURACY: 5,
  MAX_ACCURACY: 50,

  SPEED_BUFFER_SIZE: 5,
  MAX_CONSECUTIVE_INVALID_SPEEDS: 3,

  ACTIVE_SPEED_THRESHOLD: 4.16667, // 15 km/h
  PASSIVE_SPEED_THRESHOLD: 2.77778, // 10 km/h
  PASSIVE_TIMEOUT_MS: 300000, // 5 minutes
  PASSIVE_START_CONFIRMATION_COUNT: 2,
  PASSIVE_START_CONFIRMATION_WINDOW_MS: 120000, // 2 minutes
  LOW_SPEED_PROGRESS_RESET_DISTANCE_KM: 0.15, // 150m movement keeps journey active
  LOW_SPEED_PROGRESS_RESET_MIN_DISPLACEMENT_KM: 0.025, // 25m verified displacement prevents GPS drift resets
  ACTIVE_STOP_NON_AUTOMOTIVE_CONFIRMATION_MS: 30000, // sustained non-automotive signal for 30s
  ACTIVE_STOP_NON_AUTOMOTIVE_MAX_SPEED_MS: 1.80556, // 6.5 km/h

  PASSIVE_COARSE_DISTANCE_INTERVAL: 50, // meters
  PASSIVE_COARSE_DEFERRED_UPDATES_INTERVAL_MS: 20000, // 20s
  PASSIVE_COARSE_DEFERRED_UPDATES_DISTANCE: 100, // meters
  PASSIVE_PROBE_DISTANCE_INTERVAL: 10, // meters
  PASSIVE_PROBE_DEFERRED_UPDATES_INTERVAL_MS: 0, // no deferred batching in probe mode
  PASSIVE_PROBE_DEFERRED_UPDATES_DISTANCE: 0, // no deferred batching in probe mode
  PASSIVE_PROBE_DURATION_MS: 45000, // 45s
  PASSIVE_PROBE_TRIGGER_SPEED_THRESHOLD: 3.33333, // 12 km/h
  PASSIVE_PROBE_MIN_DISPLACEMENT_KM: 0.025, // 25m
  PASSIVE_ACTIVITY_PROBE_MIN_CONFIDENCE_SCORE: 2, // 1=low, 2=medium, 3=high
  PASSIVE_ACTIVITY_PROBE_DEBOUNCE_MS: 3000, // sustained automotive signal for 3s
  PASSIVE_ACTIVITY_PROBE_COOLDOWN_MS: 60000, // avoid rapid probe flapping
};

export const {
  MIN_VALID_SPEED,
  MAX_VALID_SPEED,
  MIN_ACCURACY,
  MAX_ACCURACY,
  SPEED_BUFFER_SIZE,
  MAX_CONSECUTIVE_INVALID_SPEEDS,
  ACTIVE_SPEED_THRESHOLD,
  PASSIVE_SPEED_THRESHOLD,
  PASSIVE_TIMEOUT_MS,
  PASSIVE_START_CONFIRMATION_COUNT,
  PASSIVE_START_CONFIRMATION_WINDOW_MS,
  LOW_SPEED_PROGRESS_RESET_DISTANCE_KM,
  LOW_SPEED_PROGRESS_RESET_MIN_DISPLACEMENT_KM,
  ACTIVE_STOP_NON_AUTOMOTIVE_CONFIRMATION_MS,
  ACTIVE_STOP_NON_AUTOMOTIVE_MAX_SPEED_MS,
  PASSIVE_COARSE_DISTANCE_INTERVAL,
  PASSIVE_COARSE_DEFERRED_UPDATES_INTERVAL_MS,
  PASSIVE_COARSE_DEFERRED_UPDATES_DISTANCE,
  PASSIVE_PROBE_DISTANCE_INTERVAL,
  PASSIVE_PROBE_DEFERRED_UPDATES_INTERVAL_MS,
  PASSIVE_PROBE_DEFERRED_UPDATES_DISTANCE,
  PASSIVE_PROBE_DURATION_MS,
  PASSIVE_PROBE_TRIGGER_SPEED_THRESHOLD,
  PASSIVE_PROBE_MIN_DISPLACEMENT_KM,
  PASSIVE_ACTIVITY_PROBE_MIN_CONFIDENCE_SCORE,
  PASSIVE_ACTIVITY_PROBE_DEBOUNCE_MS,
  PASSIVE_ACTIVITY_PROBE_COOLDOWN_MS,
} = DEFAULT_GPS_CONFIG;
